# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'id_rsa.pub'

- task: TerraformCLI@1
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(cleint_secret) -var cssh_public_key=$(publickey.securefilepath)'
    backendType: 'azurerm'
    backendServiceArm: 'Free Trial(1038d8e4-117d-46d9-add3-21978970ecad)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'New123'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccoutmayank1500ms'
    backendAzureRmContainerName: 'accountmayank1500ms'
    backendAzureRmKey: 'k8s.tfstate'
    allowTelemetryCollection: true