# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: First
    steps:
     - bash: echo build first stage-first job
  - job: second
    steps:
    - bash: echo build first stage-second job

- stage: Dev
  jobs:
  - job: first
    steps:
    - bash : echo second Stage-first job       
- stage: QA
  jobs:
  - job: First
    steps:
    - script: echo stage 3 job 1
      displayName: 'Run a one-line script'

    - script: |
       echo Add other tasks to build, test, and deploy your project.
       echo See https://aka.ms/yaml
      displayName: 'Run'
  - job: Second
    steps:
    - script: echo stage 3 job 2